---
language: node_js
node_js:
  - "10"

dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn test

jobs:
  include:
    # trick the above script into running
    - env: NOTHING=1

    - if: branch = master AND type = pull_request
      stage: "ember-cli-update"
      name: "ember-cli-update"
      script:
        - git checkout $TRAVIS_PULL_REQUEST_SHA
        - git checkout -B $TRAVIS_PULL_REQUEST_BRANCH
        - git remote set-url origin https://$GITHUB_TOKEN@github.com/$TRAVIS_PULL_REQUEST_SLUG.git
        - npx https://github.com/kellyselden/ember-cli-update-action.git#semver:^1.5.4 --pull-request-url https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST --autofix-command "npm run lint:js -- --fix"
